from datetime import date

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel

# Load OPENAI_API_KEY (and other settings) from the .env file.
load_dotenv()

# ============================================================
# 1. CREATE THE OPENAI CLIENT
# ============================================================

# The OpenAI client reads OPENAI_API_KEY from your environment.
#
# timeout=30
#   If the API doesn't respond within 30 seconds, stop waiting.
#
# max_retries=3
#   The SDK can retry certain temporary failures such as
#   rate limits or network problems.
#
client = OpenAI(
    timeout=30,
    max_retries=3
)


# The model we will use for this project.
MODEL = "gpt-4o-mini"


# ============================================================
# 2. SYSTEM PROMPT
# ============================================================

# This is the LLM's "job description".
#
# We are telling it:
#
# - What role it has
# - What database dialect it should use
# - What it is allowed to query
# - What "revenue" means
# - What to do when it cannot answer
#
SYSTEM_PROMPT = """
You are a senior analytics engineer who writes SQLite SQL.

Today's date is {today}.

Rules:

- Use ONLY the tables and columns in the schema below.
  Never invent tables or columns.

- Write exactly one read-only statement:
  SELECT, or WITH ... SELECT.

- Business definition:
  revenue = order_items.quantity * products.unit_price,
  excluding orders whose status is 'cancelled' or 'returned',
  unless the user says otherwise.

- Use SQLite date functions such as date() and strftime().

- Use the exact allowed values shown in the schema comments
  when filtering text columns.

- If the question cannot be answered from this schema:
  set is_answerable to false,
  set sql to an empty string,
  and explain what data is missing.

<schema>
{schema}
</schema>
"""


# ============================================================
# 3. DEFINE THE STRUCTURED OUTPUT
# ============================================================

# We DON'T want the LLM to simply return:
#
# "SELECT city, COUNT(*) FROM customers..."
#
# Instead, we want a predictable structure.
#
# The model must give us four fields:
#
# is_answerable
# sql
# tables_used
# explanation
#
class SQLResponse(BaseModel):

    # Can the database answer the user's question?
    is_answerable: bool

    # The SQL query generated by the model.
    sql: str

    # Tables that the model believes it used.
    tables_used: list[str]

    # Short explanation of what the SQL does.
    explanation: str


# ============================================================
# 4. JSON SCHEMA FOR OPENAI STRUCTURED OUTPUT
# ============================================================

# This tells the API exactly what JSON structure we expect.
#
# The important part is:
#
# "strict": True
#
# This makes the model follow the structure instead of
# returning arbitrary JSON/text.
#
SQL_SCHEMA = {

    "type": "object",

    "properties": {

        "is_answerable": {
            "type": "boolean"
        },

        "sql": {
            "type": "string"
        },

        "tables_used": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },

        "explanation": {
            "type": "string"
        },
    },

    # Every field is mandatory.
    "required": [
        "is_answerable",
        "sql",
        "tables_used",
        "explanation"
    ],

    # Don't allow the model to invent additional fields.
    "additionalProperties": False,
}


# ============================================================
# 5. GENERATE SQL
# ============================================================

def generate_sql(
    question,
    schema_text,
    history=None,
    error_feedback=None
):
    """
    Convert a natural-language question into structured SQL.

    Parameters:
        question:
            The user's current question.

        schema_text:
            Database schema generated by schema.py.

        history:
            Previous question → SQL pairs.

        error_feedback:
            Database error from a previous failed SQL query.

    Returns:
        result
        usage
    """


    # --------------------------------------------------------
    # 6. START BUILDING THE MESSAGE LIST
    # --------------------------------------------------------

    messages = [

        {
            "role": "system",

            "content": SYSTEM_PROMPT.format(
                today=date.today().isoformat(),
                schema=schema_text
            ),
        }
    ]


    # --------------------------------------------------------
    # 7. ADD SHORT-TERM MEMORY
    # --------------------------------------------------------

    # We only send the last 3 conversations.
    #
    # Why?
    #
    # Suppose the user asks:
    #
    #   "Which city has the most customers?"
    #
    # Then:
    #
    #   "Now only for Delhi."
    #
    # The second question depends on the first question.
    #
    # By giving the model the previous question and SQL,
    # it has enough context to understand the follow-up.
    #
    # We deliberately limit this to 3 turns to control
    # token usage.
    #
    for turn in (history or [])[-3:]:

        messages.append(
            {
                "role": "user",
                "content": turn["question"]
            }
        )

        messages.append(
            {
                "role": "assistant",
                "content": f"SQL used: {turn['sql']}"
            }
        )


    # --------------------------------------------------------
    # 8. PREPARE THE CURRENT QUESTION
    # --------------------------------------------------------

    content = question


    # --------------------------------------------------------
    # 9. ADD DATABASE ERROR IF THIS IS A RETRY
    # --------------------------------------------------------

    # This won't be used immediately.
    #
    # Later, Module 7 will use this for self-correction.
    #
    # Example:
    #
    # First SQL:
    #
    # SELECT customer_name FROM customers;
    #
    # Database says:
    #
    # no such column: customer_name
    #
    # We send that error back to the model and ask it
    # to produce corrected SQL.
    #
    if error_feedback:

        content += (
            f"\n\n"
            f"Your previous SQL failed with this database error:\n"
            f"{error_feedback}\n"
            f"Return a corrected query."
        )


    # Add the current user question.
    messages.append(
        {
            "role": "user",
            "content": content
        }
    )


    # ========================================================
    # 10. CALL OPENAI
    # ========================================================

    response = client.chat.completions.create(

        model=MODEL,

        # Temperature 0 means we want deterministic,
        # predictable SQL generation.
        temperature=0,

        messages=messages,

        # Ask OpenAI for structured JSON output.
        response_format={
            "type": "json_schema",

            "json_schema": {
                "name": "sql_response",
                "strict": True,
                "schema": SQL_SCHEMA
            },
        },
    )


    # ========================================================
    # 11. VALIDATE THE RESPONSE WITH PYDANTIC
    # ========================================================

    # The LLM response is JSON text.
    #
    # Pydantic converts and validates it against SQLResponse.
    #
    result = SQLResponse.model_validate_json(
        response.choices[0].message.content
    )


    # Return both:
    #
    # result → generated SQL + metadata
    #
    # usage → token usage information
    #
    return result, response.usage

if __name__ == "__main__":
    # Load the database schema
    from schema import get_schema_context

    schema_text, tables = get_schema_context("DB_Scripts/retail.db")

    # Ask a simple question
    result, usage = generate_sql(
    "How many customers are there in total?",
    schema_text
)

    print("\n--- Generated Result ---")
    print(result)

    print("\n--- Token Usage ---")
    print(usage)